import { addArrowBoxStories } from './arrowbox/ArrowBoxStories';
import { addBoxStories } from './box/BoxStories';
import { addButtonsStories } from './buttons';
import { addColorsStories } from './colors';
import { addDecorationsStories } from './decorations';
import { addFormStories } from './form';
import { addIconStories } from './icon/IconStories';
import { addInteractionStories } from './interaction';
import { addLabelStories } from './label/LabelStories';
import { addLayoutStories } from './layout';
import { addPopupStories } from './popup/PopupStories';
import { addProgressStories } from './progress';
import { addSliderStories } from './slider';
import { addGridHooksStories } from './table/GridHooksStories';
import { addTableStories } from './table/TableStories';
import { addTextStories } from './text';

addArrowBoxStories();
addBoxStories();
addButtonsStories();
addColorsStories();
addDecorationsStories();
addFormStories();
addGridHooksStories();
addIconStories();
addInteractionStories();
addLabelStories();
addLayoutStories();
addPopupStories();
addProgressStories();
addSliderStories();
addTableStories();
addTextStories();
