import React from 'react';
import './initFontAwesome';
import { addMultipleOptionsStories } from './form/MultipleOptionsStories';
import { addSpaceStories } from './layout/SpaceStories';
import { addSliderStories } from './slider/SliderStories';
import { addTimeSliderStories } from './slider/TimeSliderStories';
import { addStandardButtonStories } from './buttons/StandardButtonStories';
import { addSimpleCheckboxStories } from './form/SimpleCheckboxStories';
import { addIndentStories } from './layout/IndentStories';
import { addSpacingStories } from './layout/SpacingStories';
import { addArrowBoxStories } from './box/ArrowBoxStories';
import { addProgressIndicatorStories } from './progress/ProgressIndicatorStories';
import { addBoatProgressIndicatorStories } from './progress/BoatProgressIndicatorStories';
import { addSmallButtonStories } from './buttons/SmallButtonStories';
import { addFlatButtonStories } from './buttons/FlatButtonStories';
import { addDefaultTextStories } from './text/TextStories';
import { addRowStories } from './layout/RowStories';
import { addColumnStories } from './layout/ColumnStories';
import { addBorderStories } from './decorations/BorderStories';
import { addShadowStories } from './decorations/ShadowStories';
import { addClickableStories } from './interaction/ClickableStories';
import { addLabelStories } from './label/LabelStories';
import { addTableStories } from './table/TableStories';
import { addTextInputStories } from './form/TextInputStories';
import { addCalendarStories } from './form/CalendarStories';
import { addDateTimeInputStories } from './form/DateTimeInputStories';
import { addCardStories } from './card/CardStories';

addMultipleOptionsStories();
addSpaceStories();
addSliderStories();
addTimeSliderStories();
addFlatButtonStories();
addSmallButtonStories();
addStandardButtonStories();
addSimpleCheckboxStories();
addIndentStories();
addLabelStories();
addSpacingStories();
addArrowBoxStories();
addProgressIndicatorStories();
addBoatProgressIndicatorStories();
addDefaultTextStories();
addRowStories();
addColumnStories();
addBorderStories();
addShadowStories();
addClickableStories();
addTableStories();
addTextInputStories();
addCalendarStories();
addDateTimeInputStories();
addCardStories();
