import { addBoxStories } from './box';
import { addButtonsStories } from './buttons';
import { addCardStories } from './card/CardStories';
import { addColorsStories } from './colors';
import { addDecorationsStories } from './decorations';
import { addFormStories } from './form';
import './initFontAwesome';
import { addInteractionStories } from './interaction';
import { addLabelStories } from './label/LabelStories';
import { addLayoutStories } from './layout';
import { addPopupStories } from './popup/PopupStories';
import { addProgressStories } from './progress';
import { addSliderStories } from './slider';
import { addGridHooksStories } from './table/GridHooksStories';
import { addTableStories } from './table/TableStories';
import { addTextStories } from './text';

addBoxStories();
addButtonsStories();
addCardStories();
addColorsStories();
addDecorationsStories();
addFormStories();
addGridHooksStories();
addInteractionStories();
addLabelStories();
addLayoutStories();
addPopupStories();
addProgressStories();
addSliderStories();
addTableStories();
addTextStories();
