import { library } from '@fortawesome/fontawesome-svg-core';
import { fab } from '@fortawesome/free-brands-svg-icons';
import {
    faAngleDoubleLeft,
    faAngleDoubleRight,
    faBolt,
    faCalendarCheck,
    faCaretDown,
    faCheck,
    faCheckSquare,
    faChevronDown,
    faChevronUp,
    faCircle,
    faClock,
    faClone,
    faCoffee,
    faColumns,
    faExclamationCircle,
    faExclamationTriangle,
    faFire,
    faInfoCircle,
    faPaw,
    faPencilAlt,
    faPlus,
    faRegistered,
    faShip,
    faSignOutAlt,
    faSortDown,
    faSortUp,
    faSync,
    faThLarge,
    faUser,
} from '@fortawesome/free-solid-svg-icons';
import {
    faCheckCircle,
    faCircle as farCircle,
} from '@fortawesome/free-regular-svg-icons';

library.add(
    fab,
    faCheckSquare,
    faCoffee,
    faSync,
    faClone,
    faPlus,
    faCheck,
    faCircle,
    farCircle,
    faShip,
    faInfoCircle,
    faPencilAlt,
    faAngleDoubleLeft,
    faAngleDoubleRight,
    faChevronUp,
    faChevronDown,
    faSortUp,
    faSortDown,
    faColumns,
    faCaretDown,
    faClock,
    faPaw,
    faFire,
    faBolt,
    faUser,
    faExclamationTriangle,
    faExclamationCircle,
    faCalendarCheck,
    faSignOutAlt,
    faCheckCircle,
    faRegistered,
    faThLarge,
);
