import { library } from '@fortawesome/fontawesome-svg-core';
import { fab } from '@fortawesome/free-brands-svg-icons';
import {
  faCheckCircle,
  faCircle as farCircle,
} from '@fortawesome/free-regular-svg-icons';
import {
  faAngleDoubleRight,
  faBolt,
  faCalendarCheck,
  faCaretDown,
  faCaretLeft,
  faCaretRight,
  faCaretUp,
  faCheck,
  faCheckSquare,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faChevronUp,
  faCircle,
  faClock,
  faClone,
  faCoffee,
  faColumns,
  faExclamationCircle,
  faExclamationTriangle,
  faFire,
  faInfoCircle,
  faPaw,
  faPencilAlt,
  faPlus,
  faRegistered,
  faShip,
  faSignOutAlt,
  faSortDown,
  faSortUp,
  faSync,
  faThLarge,
  faUser,
} from '@fortawesome/free-solid-svg-icons';

library.add(
  fab,
  faCheckSquare,
  faCoffee,
  faSync,
  faClone,
  faPlus,
  faCheck,
  faCircle,
  farCircle,
  faShip,
  faInfoCircle,
  faPencilAlt,
  faAngleDoubleRight,
  faChevronUp,
  faChevronLeft,
  faChevronRight,
  faChevronDown,
  faSortUp,
  faSortDown,
  faColumns,
  faCaretDown,
  faCaretLeft,
  faCaretRight,
  faCaretUp,
  faClock,
  faPaw,
  faFire,
  faBolt,
  faUser,
  faExclamationTriangle,
  faExclamationCircle,
  faCalendarCheck,
  faSignOutAlt,
  faCheckCircle,
  faRegistered,
  faThLarge,
);
